/** Bounded desktop/phone checks using only temporary bridge credentials/state. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {dirname, basename, join, extname, resolve, sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {mkdtemp, readFile, mkdir, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import http from 'node:http';
import net from 'node:net';

const root=dirname(dirname(fileURLToPath(import.meta.url))), require=createRequire(import.meta.url);
let playwright;
try {playwright=require('playwright');} catch {playwright=require(join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const python=process.env.DOTS_TEST_PYTHON||join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const temp=await mkdtemp(join(tmpdir(),'dots-beta-ui-')), artifacts=join(root,'tests/artifacts');
await mkdir(artifacts,{recursive:true});
const environment=Object.fromEntries(Object.entries(process.env).filter(([key])=>!key.startsWith('DOTS_')&&key!=='PYTHONPATH'));
const probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
const origin=`http://127.0.0.1:${port}`;
const child=spawn(python,['-m','dots_on_paper','--data-dir',temp],{cwd:temp,env:{...environment,DOTS_PORT:String(port),DOTS_PUBLIC_URL:origin},stdio:'ignore'});
const siteRoot=join(root,'site/dist');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.ttf':'font/ttf','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'};
const site=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const file=resolve(siteRoot,'.'+decodeURIComponent(url.pathname)+(url.pathname.endsWith('/')?'index.html':''));if(!file.startsWith(siteRoot+sep)){res.writeHead(403);res.end();return;}const bytes=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream'});res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(resolve=>site.listen(0,'127.0.0.1',resolve));const publicOrigin=`http://127.0.0.1:${site.address().port}/dotsonpaper/`;
let browser;
try{
  for(let attempt=0;attempt<100;attempt++){try{if((await fetch(origin+'/api/health')).ok)break;}catch{}await new Promise(resolve=>setTimeout(resolve,100));}
  const keys=JSON.parse(await readFile(join(temp,'credentials.json'),'utf8'));
  browser=await playwright.chromium.launch({channel:'chrome',headless:true});
  const errors=[], requests=[];
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>requests.push({url:request.url(),body:request.postData()||''}));
  await page.goto(publicOrigin);await page.locator('#demo').scrollIntoViewIfNeeded();
  await page.locator('#skip-preview').click();
  assert.match(await page.locator('#screen-transcript').textContent(),/Site review finished/);
  await page.locator('[data-mode="full_conversation"]').click();await page.locator('#skip-preview').click();
  assert.match(await page.locator('#screen-transcript').textContent(),/Nothing sent/);
  await page.screenshot({path:join(artifacts,'beta-site-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal((await page.locator('#demo-title').innerText()).replace(/\s+/g,' ').trim(),'Watch a thought land.');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:join(artifacts,'beta-site-mobile.png'),fullPage:true});
  await page.goto(publicOrigin+'try/');await page.evaluate(()=>window.dotDemo.allDotsReady);await page.evaluate(()=>window.dotDemo.ready);
  assert.equal(await page.locator('.masthead-note').isVisible(),true);
  assert.match(await page.locator('.masthead-note').innerText(),/Browser simulation/);
  const note='Personal browser test note.\n\n- Check the report.\n- Bring the parcel.';
  await page.locator('#answer').fill(note);await page.locator('#answer-editor button').click();
  assert.equal(await page.locator('#trial-transcript').textContent(),note);
  for(const dot of ['curious','bookish','cool','artist'])await page.locator(`[data-dot="${dot}"]`).click();
  const downloadPromise=page.waitForEvent('download');await page.locator('#save-screen').click();const download=await downloadPromise;
  const png=await readFile(await download.path());assert.equal(png.readUInt32BE(16),1872);assert.equal(png.readUInt32BE(20),1404);
  assert.equal(requests.some(request=>request.url.includes('Personal')||request.body.includes(note)),false);
  assert.equal(await page.evaluate(()=>localStorage.length),0);
  await page.screenshot({path:join(artifacts,'beta-trial-mobile.png'),fullPage:true});
  await page.locator('#share-sample').click();assert.doesNotMatch(await page.locator('#trial-transcript').textContent(),/Personal/);
  await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:join(artifacts,'beta-trial-desktop.png'),fullPage:true});
  await page.goto(origin);await page.locator('#credentials').setInputFiles(join(temp,'credentials.json'));
  await page.waitForFunction(()=>document.querySelector('#status').classList.contains('connected'));
  await page.locator('#test-text').fill('A short useful result from the local UI test.');await page.locator('#test-card').click();
  await page.waitForFunction(()=>document.querySelector('#step-try').dataset.done==='true');
  assert.equal(await page.locator('#step-source').getAttribute('data-done'),'false');
  await page.locator('#source-setup').evaluate(element=>element.open=true);await page.locator('#client-config').click();
  await page.locator('#client-json').waitFor({state:'visible'});const config=JSON.parse(await page.locator('#client-json').textContent());
  assert.equal(JSON.stringify(config).includes(keys.api_token),false);
  const client=config.mcpServers['dots-on-paper'];
  const events=[{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'beta-verification-client',version:'1'}}},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'publish_dot_reply',arguments:{text:'MCP configuration verified. The result stays visible.',source:'Verification client'}}}];
  const rpc=spawn(client.command,client.args,{env:{...environment,...client.env},stdio:['pipe','pipe','pipe']});let response='';rpc.stdout.on('data',data=>response+=data);rpc.stdin.end(events.map(event=>JSON.stringify(event)).join('\n')+'\n');await new Promise((resolve,reject)=>{rpc.on('exit',code=>code===0?resolve():reject(new Error('Generated MCP client failed')));});
  assert.equal(JSON.parse(response.trim().split('\n').at(-1)).result.isError,false);
  assert.equal(JSON.parse(response.trim().split('\n').at(-1)).result.structuredContent.title,'Reply');
  await page.waitForFunction(()=>document.querySelector('#step-source').dataset.done==='true');
  await page.screenshot({path:join(artifacts,'beta-bridge-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.locator('#full-result').evaluate(element=>element.open=true);await page.screenshot({path:join(artifacts,'beta-bridge-mobile.png'),fullPage:true});
  await page.locator('#clear-display').click();await page.waitForFunction(()=>document.querySelector('#reply-label').textContent==='Ready for your dot');
  await page.locator('#restore').click();await page.waitForFunction(()=>document.querySelector('#reply-label').textContent.startsWith('Reply'));
  page.on('dialog',dialog=>dialog.accept());await page.locator('#clear-history').click();await page.waitForFunction(()=>document.querySelector('#transcript').textContent==='No completed result stored.');
  assert.equal(await page.locator('#token').inputValue(),'');assert.deepEqual(errors,[]);
  const reduced=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await reduced.goto(publicOrigin);await reduced.locator('#demo').scrollIntoViewIfNeeded();await reduced.waitForTimeout(250);assert.equal(await reduced.locator('#screen').getAttribute('src'),'./assets/frames/cool-completed-last_reply.png');
  console.log('Beta browser checks passed: desktop/phone layout, transcript, modes, reduced motion, private editable trial, PNG export, safe sample, local test/source separation, generated installed MCP config, restore and history clearing.');
}finally{await browser?.close();if(child.exitCode===null&&child.signalCode===null){child.kill();await new Promise(resolve=>child.once('exit',resolve));}await new Promise(resolve=>site.close(resolve));assert.ok(resolve(temp).startsWith(resolve(tmpdir())+sep)&&basename(temp).startsWith('dots-beta-ui-'));await rm(temp,{recursive:true,force:true});}
